---
# ข้อความเนื้อหา
# Content Message
Content: "§f=========================\n\n§aWelcome to §cMC§f-§6Car§erot§aCraft\n  §f- §1Facebook: §bNapon Kritteeranan\n  §f- §aLine: napolgamer_th\n  §f- §cYou§fTube: §eNapolGamer TH\n§f========================="

# ปุ่ม
# Button
Button: "เข้าใจแล้ว"
...
