---
# ข้อความเนื้อหา
# Content Message
Content: "§f=========================\n\n§eWelcome to §fZetsu §cMC §aS1\n\n §eWe offer you:\n §7- §eSkyBlock\n §7- §eSurvival\n §7- §ePvP\n §7-§e Factions\n §aPlease do not break the Rules\n here are the rules!\n\n §7- §eDo not grief Players House in survival!\n §7- §eDo not Spam in the chat !\n §7- §ePlease do not racist, sexism in the server!\n §aThats all for the rules !\n\n §aPlease play properly\n §e Thank you for reading !\n\n §f========================="

# ปุ่ม
# Button
Button: "§l§ePLAY§r"
...
