---
# ข้อความเนื้อหา
# Content Message
Content: "§f=========================\n\n§aWelcome to §fZetsu §ePE\n \n §7-= §fRules §7=-\n - Do not grief anybody house\n - Please do not swear very bad\n if somebody got caught will be kick !\n \n§f========================="

# ปุ่ม
# Button
Button: "§l§bPLAY"
...
